server:
  port: 8189
  servlet:
    context-path: /titanic

spring:
  application:
    name: titanic
#  cache:
#    type: redis
#    cache-names: redis-cache
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: parole
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: titanic
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: development, production
    drop-first: false
logging:
  level:
    org.springframework: INFO
    org.pablos.backend: DEBUG
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 5
  file:
    name: ./logs/${spring.application.name}.log