server:
  port: 8189
  servlet:
    context-path: /titanic
spring:
  application:
    name: titanic
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: titanic
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: development, production
    drop-first: false
logging:
  level:
    org.springframework: INFO
  file:
    name: ./logs/${spring.application.name}.log